### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mattthew3000** [rubenvillegas/cvpr2018nkn#6]
Dear authors,
To run the codes, it seems it is required to have all the training samples.  However, downloading and processing all the 1656 samples one-by-one can be really tedious. Would you please help us if you have any suggestion to facilitate the collecting of training samples. Sending a  pre-trained model is highly appreciated

**Comment by rubenvillegas** [comment]
To download the data from the mixamo data, we wrote a script that crawled each page in the website. Last time we tried to use it again, it didn’t work so they must have patched that (we tried about a year ago). You are going to have to do something similar to speed up the download. We also cannot share the downloaded training data because mixamo did not allow us to do that.

In regards to share the model, we cannot do it because it’s under patent but we provide instructions to replicate the results.
